// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Donem_Projesi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Model.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("musteri");
                });

            modelBuilder.Entity("Entities.Model.Sepet", b =>
                {
                    b.Property<int>("SepetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SepetId"));

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("SepetId");

                    b.ToTable("Sepet");
                });

            modelBuilder.Entity("Entities.Model.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"));

                    b.Property<int>("_musteriId")
                        .HasColumnType("int");

                    b.HasKey("SiparisID");

                    b.HasIndex("_musteriId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Entities.Model.Urunler", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<int>("Adet_Sayisi")
                        .HasColumnType("int");

                    b.Property<int>("BolgeID")
                        .HasColumnType("int");

                    b.Property<string>("Marka_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parca_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Entities.Model.İade", b =>
                {
                    b.Property<int>("iade_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iade_id"));

                    b.Property<int>("BolgeID_iade")
                        .HasColumnType("int");

                    b.Property<int>("Siparis_iadeSiparisID")
                        .HasColumnType("int");

                    b.Property<int>("UrunId_iade")
                        .HasColumnType("int");

                    b.Property<int>("siparis_iade")
                        .HasColumnType("int");

                    b.Property<int>("urun_iadeUrunId")
                        .HasColumnType("int");

                    b.HasKey("iade_id");

                    b.HasIndex("Siparis_iadeSiparisID");

                    b.HasIndex("urun_iadeUrunId");

                    b.ToTable("İade");
                });

            modelBuilder.Entity("Entities.Model.Siparis", b =>
                {
                    b.HasOne("Entities.Model.Musteri", "_musteri")
                        .WithMany()
                        .HasForeignKey("_musteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_musteri");
                });

            modelBuilder.Entity("Entities.Model.İade", b =>
                {
                    b.HasOne("Entities.Model.Siparis", "Siparis_iade")
                        .WithMany()
                        .HasForeignKey("Siparis_iadeSiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Model.Urunler", "urun_iade")
                        .WithMany()
                        .HasForeignKey("urun_iadeUrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis_iade");

                    b.Navigation("urun_iade");
                });
#pragma warning restore 612, 618
        }
    }
}
